{% set name = "aiohttp-retry" %}
{% set version = "2.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiohttp_retry-{{ version }}.tar.gz
  sha256: 92c47f1580040208bac95d9a8389a87227ef22758530f2e3f4683395e42c41b5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiohttp
    - python >={{ python_min }}

test:
  imports:
    - aiohttp_retry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/inyutin/aiohttp_retry
  summary: Simple retry client for aiohttp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isidentical
    - efiop
